### ISSUE TITLE
Move retrieval of user data to op-be-user

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-auth#13]
We are retrieving user data (password, username, etc.) directly within our auth service. We should move that process to the op-be-auth service.

**Comment by Sddilora** [comment]
@Feyzanrs can you please merge the [first/hsm/1/create-first](https://github.com/octoposprime/op-be-auth/tree/first/hsm/1/create-first) into phase1, then close the issue.

**Comment by Feyzanrs** [comment]
> @Feyzanrs can you please merge the [first/hsm/1/create-first](https://github.com/octoposprime/op-be-auth/tree/first/hsm/1/create-first) into phase1, then close the issue.

with great pleasure :)

**Comment by Sddilora** [comment]
> > @Feyzanrs can you please merge the [first/hsm/1/create-first](https://github.com/octoposprime/op-be-auth/tree/first/hsm/1/create-first) into phase1, then close the issue.
> 
> with great pleasure :)

Thanks <3 :)
