### ISSUE TITLE
Update Config Files for Service Hosts

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-auth#22]
We need to update the configuration settings in the `config/internal.yml` and `config/internal_test.yml` files to reflect changes in our service architecture. The updates involve adding new authentication service host and port configurations and removing existing user service settings to streamline our infrastructure setup.

## Path of the files to be updated
- config/internal.yml
- config/internal_test.yml

Note: Please ensure that the changes are made in both files.

## Changes to be made
- Add:
  ```yaml
  authentication_host: "op-be-auth"
  authentication_port: "18080"

**The changes will be merged into the first/hsm/1/create-first branch first. Therefore, set the base branch of the pull request as first/hsm/1/create-first.**

**Comment by Sddilora** [comment]
I made changes on the issue, I realized that we need to use the user host and port to communicate with the user service, and they need to stay here.
