### ISSUE TITLE
Update Config for Authentication in internal_local.yml

### ISSUE THREAD

**Issue by Feyzanrs** [octoposprime/op-be-auth#23]
We need to update our local configuration settings in the config/internal_local.yml file to reflect the changes in our service architecture. This update includes adding new authentication service configurations.

## Paths to Update:
config/internal_local.yml

## Changes Required:

- Add:
```yml
authentication_host: "localhost"
authentication_port: "18084"
```

## Additional Note:
Please ensure that the new authentication settings are added under the grpc section of the file. This is critical to maintain the correct structure and functionality in our local development environment.

**The changes will be merged into the first/hsm/1/create-first branch first. Therefore, set the base branch of the pull request as first/hsm/1/create-first.**

**Comment by Sddilora** [comment]
I made changes on the issue, I realized that we need to use the user host and port to communicate with the user service, and they need to stay here.
