### ISSUE TITLE
Rm user-specific files from int/pre/adpt/cmd

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-auth#9]
Remove `user.go` and `user_test.go` from "https://github.com/octoposprime/op-be-auth/tree/first/hsm/1/create-first/internal/application/presentation/adapter/command"

**The changes will be merged into the "/first/hsm/1/create-first" branch first. Therefore, set the base branch of the pull request as /first/hsm/1/create-first.**

**Comment by Feyzanrs** [comment]
In the branch first/hsm/1/create-first, I removed the files user.go and user_test.go with commit number `0f930493a8ab6d26783659c9c61eb80ef7d9777f`.
